export { default as Hero } from "./hero/Hero";
export { default as About } from "./about/About";
export { default as Education } from "./education/Education";
export { default as Tech } from "./tech/Tech";
export { default as Projects } from "./projects/Projects";
export { default as Experience } from "./experience/Experience";
export { default as Contact } from "./contact/Contact";
export { default as Footer } from "./page/Footer";
export { default as Navbar } from "./page/Navbar";
